package edu.uestc.cilab.repository;

import edu.uestc.cilab.entity.OfficialContent;
import edu.uestc.cilab.entity.OfficialContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OfficialContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    int countByExample(OfficialContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    int deleteByExample(OfficialContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    @Delete({
        "delete from official_content",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    @Insert({
        "insert into official_content (id, official_document_id, ",
        "content_address)",
        "values (#{id,jdbcType=INTEGER}, #{officialDocumentId,jdbcType=INTEGER}, ",
        "#{contentAddress,jdbcType=VARCHAR})"
    })
    int insert(OfficialContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    int insertSelective(OfficialContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    List<OfficialContent> selectByExample(OfficialContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, official_document_id, content_address",
        "from official_content",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    OfficialContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfficialContent record, @Param("example") OfficialContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfficialContent record, @Param("example") OfficialContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfficialContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    @Update({
        "update official_content",
        "set official_document_id = #{officialDocumentId,jdbcType=INTEGER},",
          "content_address = #{contentAddress,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OfficialContent record);

    @Select({
            "select * from official_content where official_document_id = #{officialDocumentId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    List<OfficialContent> selectAlldata(Integer officialDocumentId);
}