package edu.uestc.cilab.entity;

import edu.uestc.cilab.constant.DateConstant;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotNull;
import java.util.Date;

public class OfficialDocument {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.official_box_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案盒子id",required = true)
    private Integer officialBoxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.box_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "档号（原盒号）",required = true)
    private String boxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文号（原档案编号可以不填）")
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.title
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "题名",required = true)
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.page_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "页数",required = true)
    private String pageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.responsible_person
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "责任人",required = true)
    private String responsiblePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.keep_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "保管期限",required = true,allowableValues = "永久,100年,50年,30年,10年,长期,短期")
    @NotNull(message = "保管期限不能为空")
    private String keepTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.document_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文件日期",required = true)
    private String documentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.create_user_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "录入员",required = true)
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.gmt_create
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = DateConstant.DATE_PATTERN)
    @ApiModelProperty(hidden = true)
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.gmt_modified
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = DateConstant.DATE_PATTERN)
    @ApiModelProperty(hidden = true)
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_document
     *
     * @mbggenerated
     */
    public OfficialDocument(Integer id, Integer officialBoxId, String boxNumber, String number, String title, String pageNumber, String responsiblePerson, String keepTime, String documentTime, String createUserName, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.officialBoxId = officialBoxId;
        this.boxNumber = boxNumber;
        this.number = number;
        this.title = title;
        this.pageNumber = pageNumber;
        this.responsiblePerson = responsiblePerson;
        this.keepTime = keepTime;
        this.documentTime = documentTime;
        this.createUserName = createUserName;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_document
     *
     * @mbggenerated
     */
    public OfficialDocument() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.id
     *
     * @return the value of official_document.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.id
     *
     * @param id the value for official_document.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.official_box_id
     *
     * @return the value of official_document.official_box_id
     *
     * @mbggenerated
     */
    public Integer getOfficialBoxId() {
        return officialBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.official_box_id
     *
     * @param officialBoxId the value for official_document.official_box_id
     *
     * @mbggenerated
     */
    public void setOfficialBoxId(Integer officialBoxId) {
        this.officialBoxId = officialBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.box_number
     *
     * @return the value of official_document.box_number
     *
     * @mbggenerated
     */
    public String getBoxNumber() {
        return boxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.box_number
     *
     * @param boxNumber the value for official_document.box_number
     *
     * @mbggenerated
     */
    public void setBoxNumber(String boxNumber) {
        this.boxNumber = boxNumber == null ? null : boxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.number
     *
     * @return the value of official_document.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.number
     *
     * @param number the value for official_document.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.title
     *
     * @return the value of official_document.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.title
     *
     * @param title the value for official_document.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.page_number
     *
     * @return the value of official_document.page_number
     *
     * @mbggenerated
     */
    public String getPageNumber() {
        return pageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.page_number
     *
     * @param pageNumber the value for official_document.page_number
     *
     * @mbggenerated
     */
    public void setPageNumber(String pageNumber) {
        this.pageNumber = pageNumber == null ? null : pageNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.responsible_person
     *
     * @return the value of official_document.responsible_person
     *
     * @mbggenerated
     */
    public String getResponsiblePerson() {
        return responsiblePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.responsible_person
     *
     * @param responsiblePerson the value for official_document.responsible_person
     *
     * @mbggenerated
     */
    public void setResponsiblePerson(String responsiblePerson) {
        this.responsiblePerson = responsiblePerson == null ? null : responsiblePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.keep_time
     *
     * @return the value of official_document.keep_time
     *
     * @mbggenerated
     */
    public String getKeepTime() {
        return keepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.keep_time
     *
     * @param keepTime the value for official_document.keep_time
     *
     * @mbggenerated
     */
    public void setKeepTime(String keepTime) {
        this.keepTime = keepTime == null ? null : keepTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.document_time
     *
     * @return the value of official_document.document_time
     *
     * @mbggenerated
     */
    public String getDocumentTime() {
        return documentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.document_time
     *
     * @param documentTime the value for official_document.document_time
     *
     * @mbggenerated
     */
    public void setDocumentTime(String documentTime) {
        this.documentTime = documentTime == null ? null : documentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.create_user_name
     *
     * @return the value of official_document.create_user_name
     *
     * @mbggenerated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.create_user_name
     *
     * @param createUserName the value for official_document.create_user_name
     *
     * @mbggenerated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.gmt_create
     *
     * @return the value of official_document.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.gmt_create
     *
     * @param gmtCreate the value for official_document.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_document.gmt_modified
     *
     * @return the value of official_document.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_document.gmt_modified
     *
     * @param gmtModified the value for official_document.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}