package edu.uestc.cilab.entity;

import io.swagger.annotations.ApiModelProperty;

public class OfficialContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_content.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案内容ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_content.official_document_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案ID", required = true)
    private Integer officialDocumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_content.content_address
     *
     * @mbggenerated
     */
    @ApiModelProperty(hidden = true)
    private String contentAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    public OfficialContent(Integer id, Integer officialDocumentId, String contentAddress) {
        this.id = id;
        this.officialDocumentId = officialDocumentId;
        this.contentAddress = contentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    public OfficialContent() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_content.id
     *
     * @return the value of official_content.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_content.id
     *
     * @param id the value for official_content.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_content.official_document_id
     *
     * @return the value of official_content.official_document_id
     *
     * @mbggenerated
     */
    public Integer getOfficialDocumentId() {
        return officialDocumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_content.official_document_id
     *
     * @param officialDocumentId the value for official_content.official_document_id
     *
     * @mbggenerated
     */
    public void setOfficialDocumentId(Integer officialDocumentId) {
        this.officialDocumentId = officialDocumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_content.content_address
     *
     * @return the value of official_content.content_address
     *
     * @mbggenerated
     */
    public String getContentAddress() {
        return contentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_content.content_address
     *
     * @param contentAddress the value for official_content.content_address
     *
     * @mbggenerated
     */
    public void setContentAddress(String contentAddress) {
        this.contentAddress = contentAddress == null ? null : contentAddress.trim();
    }
}