package edu.uestc.cilab.entity;

import io.swagger.annotations.ApiModelProperty;

public class OfficialBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_box.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案盒子ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_box.box_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "盒号", required = true)
    private String boxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_box.total_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文件总数", required = false)
    private Integer totalNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_box
     *
     * @mbggenerated
     */
    public OfficialBox(Integer id, String boxNumber, Integer totalNumber) {
        this.id = id;
        this.boxNumber = boxNumber;
        this.totalNumber = totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_box
     *
     * @mbggenerated
     */
    public OfficialBox() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_box.id
     *
     * @return the value of official_box.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_box.id
     *
     * @param id the value for official_box.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_box.box_number
     *
     * @return the value of official_box.box_number
     *
     * @mbggenerated
     */
    public String getBoxNumber() {
        return boxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_box.box_number
     *
     * @param boxNumber the value for official_box.box_number
     *
     * @mbggenerated
     */
    public void setBoxNumber(String boxNumber) {
        this.boxNumber = boxNumber == null ? null : boxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_box.total_number
     *
     * @return the value of official_box.total_number
     *
     * @mbggenerated
     */
    public Integer getTotalNumber() {
        return totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_box.total_number
     *
     * @param totalNumber the value for official_box.total_number
     *
     * @mbggenerated
     */
    public void setTotalNumber(Integer totalNumber) {
        this.totalNumber = totalNumber;
    }
}